services:

  db_postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  
  # backend to update datasets daily
  backend:
    build: ./backend
    image: "lean24/bbc_backend:latest"
    depends_on:
      - db_postgres 
    
  frontend:
    build: ./frontend
    image: "lean24/bbc_frontend:latest"
    ports:
      - 8501:8501
    depends_on:
      - db_postgres 

volumes:
  db_data: 
    name: db_data
