name: 'Terraform'

on:
  push:
    branches: main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    outputs:
      instance_public_dns: ${{steps.set_dns.outputs.instance_public_dns}}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-southeast-1

    steps:
    - name: Checkout repo 
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{env.AWS_REGION}}
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false
        terraform_version: 1.10.0

    - name: Terraform Init
      id: terraform_init
      run: terraform init
    
    - name: Terraform Plan
      id: terraform_plan
      run: terraform plan
    
    - name: Terraform_Apply
      id: terraform_apply
      run: terraform apply -auto-approve

    - name: Set output
      id: set_dns
      run: |-
        echo "instance_public_dns=${{terraform output instance_public_ip}}" >> $GITHUB_OUTPUT